name: 'TofuPlan'

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      roleArn:
        required: true
        type: string
      s3bucketName:
        required: true
        type: string
      github_event_number:
        required: true
        type: string
      github_event_issue_comments_url:
        required: true
        type: string
      stack:
        required: false
        type: string
        default: "."

jobs:
  tofu:
    name: 'Plan Tofu'
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.job.outputs.job_id }}
    permissions:
      actions: read
      id-token: write
      contents: read
      pull-requests: write
    defaults:
      run:
        shell: bash
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    steps:
    # Expose and capture the job ID of the current job
    - uses: ReeganExE/github-action-job-id@v1.0
    - name: Job ID output
      id: job
      run: |
        echo ${GH_JOB_0_ID}
        echo "job_id=$GH_JOB_0_ID" >> $GITHUB_OUTPUT

    # Use the fine-grained personal access token directly
    - name: Configure GitHub Token
      run: echo "GITHUB_TOKEN=${{ env.GITHUB_TOKEN }}" >> $GITHUB_ENV

    # Configure github access
    - uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: https://oauth:${{ env.GITHUB_TOKEN }}@github.com/

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
    - run: |
        echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        echo "Current directory: $(pwd)"
        echo "Listing files in the current directory:"
        ls -la
        cd /home/runner/work/ricards-poc/ricards-poc
        ls -la
      shell: bash

    - name: Build LocalStack Docker Image
      if: ${{ inputs.action == 'start' }}
      run: |
        docker build -t localstack_local_copy:latest .
      shell: bash

    - name: Start LocalStack
      if: ${{ inputs.action == 'start' }}
      run: |
        docker run -d --name localstack_container \
        -p 127.0.0.1:4566:4566 \
        -p 127.0.0.1:4510-4559:4510-4559 \
        -v /var/run/docker.sock:/var/run/docker.sock \
        localstack_local_copy:latest
        echo "Waiting for LocalStack to be ready..."
        for i in {1..30}; do
          if curl -s http://localhost:4566/_localstack/health | grep "\"s3\": \"available\""; then
            echo "LocalStack is ready!"
            exit 0
          fi
          echo "Still waiting for LocalStack..."
          sleep 5
        done
        echo "LocalStack did not become ready in time."
        exit 1
      shell: bash

    # Terraform Validation Steps
    - name: terraform validate ${{ inputs.stack }}
      uses: dflook/tofu-validate@v1
      with:
        path: "/home/runner/work/ricards-poc/ricards-poc"
      env:
        TERRAFORM_HTTP_CREDENTIALS: |
          github.com/arvatoaws=oauth:${{ env.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        TERRAFORM_ACTIONS_GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
    - name: terraform fmt ${{ inputs.stack }}
      uses: dflook/tofu-fmt-check@v1
      with:
        path: "/home/runner/work/ricards-poc/ricards-poc"
      env:
        TERRAFORM_HTTP_CREDENTIALS: |
          github.com/arvatoaws=oauth:${{ env.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        TERRAFORM_ACTIONS_GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

    # Install the latest version of Tofu CLI
    - name: Setup Tofu
      uses: opentofu/setup-opentofu@v1
    # Initialize Terraform
    - name: Tofu Init
      run: |
        cd /home/runner/work/ricards-poc/ricards-poc
        rm -rf .terraform .terraform.lock.hcl
        tofu init -upgrade
    # Generate tofu plan
    - name: Tofu Plan ${{ inputs.stack }}
      id: tfplan
      continue-on-error: true
      run: |
        cd /home/runner/work/ricards-poc/ricards-poc
        echo "Current directory: $(pwd)"
        echo "Listing files in the current directory:"
        ls -la
        # Bash script to build tofu plan command dynamically
        COMMAND="tofu plan -input=false -no-color -out=tfplan"
        SECRETS_JSON='${{ toJson(secrets) }}'
        SECRETS=$(echo "$SECRETS_JSON" | jq -r 'keys[]')
        # Loop over each secret in the GitHub Actions environment
        for key in $SECRETS; do
          value=$(echo "$SECRETS_JSON" | jq -r ".[\"$key\"]")
          # Check if the secret name has the prefix "TF_VAR_"
          if [[ $key == TF_VAR_* ]]; then
            # Add the secret as an input variable to the tofu command
            COMMAND="$COMMAND -var '${key#TF_VAR_}=$value'"
          fi
        done
        # Execute the dynamically generated tofu command
        eval $COMMAND && tofu show -no-color tfplan | sed 's/\x27/ /g' | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > plan.txt

    # Display the plan in logs
    - name: Display ${{ inputs.stack }} plan
      run: |
        cd /home/runner/work/ricards-poc/ricards-poc
        cat tfplan

    - name: Stop LocalStack
      run: |
        docker stop $(docker ps -q --filter ancestor=localstack/localstack)